# Generated by Django 5.0.2 on 2024-02-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
